### ISSUE TITLE
Doesn't work with latest update

### ISSUE THREAD

**Issue by pastocaza** [shiraji/emoji#15]
It doesn't work anymore with update 2017.2.4 :cry: :crying_cat_face: :sob:

**Comment by shiraji** [comment]
Thanks for the reporting. Let me investigate. Did you get the error message?

**Comment by shiraji** [comment]
My 2017.2.4 Intellij IDEA works fine.

![2017-09-19 1 54 49](https://user-images.githubusercontent.com/3675458/30553930-adfea964-9cdd-11e7-98ae-0cd251304512.png)

I also checks the development version of IDEA (2017.3). It works fine, too.

Could you elaborate?

**Comment by pastocaza** [comment]
Hello!

I don't know if this was on my end but after trying everything what I did was an Invalidate Caches/Restart and it worked just fine as usual, thank you! :100: :+1: 

Edit: I'm using Ubuntu 17.04 with Java 8

**Comment by shiraji** [comment]
Awesome! Thanks for using this plugin 😄 
(I haven't had a lot of responses from users so I was thinking no one uses this plugin)

**Comment by shiraji** [comment]
Thanks for the review!!! 🙇
