### ISSUE TITLE
Show emoji in Version Control log

### ISSUE THREAD

**Issue by krissrex** [shiraji/emoji#17]
Hi! 
Would it be possible to modify the `Version Control > Log` to render the emoji like :poop: instead of `:poop:`? 

-----

**Here are two examples:**  
The bottom commit is with `yet another`-plugin you made. The top commit is from this plugin.
![image](https://user-images.githubusercontent.com/7364831/62252719-f6c45e80-b3f3-11e9-9c18-91b5be802648.png)

The new plugin renders them like system-native emojis, which look bad on windows.
It would be nice if the commit log ( `git log`) had text like `:poop:`, but intelliJ would show them like github does, with the same icons:
![image](https://user-images.githubusercontent.com/7364831/62252816-3428ec00-b3f4-11e9-963d-44e18cdca192.png)

The `git log` command renders the emoji symbol like this, which is not good:
![image](https://user-images.githubusercontent.com/7364831/62252919-7f42ff00-b3f4-11e9-86b3-ae0ca9638a1e.png)

----

(For reference: I use https://gitmoji.carloscuesta.me/ to know what emoji to add)

**Comment by shiraji** [comment]
Interesting. Let me think how I can support that in this plugin.

**Comment by shiraji** [comment]
After searching Git4Idea, it seems they don't provide us much extension points.

https://github.com/JetBrains/intellij-community/blob/master/plugins/git4idea/resources/META-INF/plugin.xml#L285-L287

So, to accomplish this feature, we need to 

* create that feature in git4idea
* create an extension point in git4idea and implement this feature in this plugin
* provide new log tool window (which is kinda too hard to maintain...)

Seems really hard to do this 🤕

**Comment by tianalemesle** [comment]
Hello, why did #19 closed this issue while it doesn't implement it ? Although I do acknowledge that the plugin wouldn't be able to implement it. Thanks
