### ISSUE TITLE
remove ":" from completion

### ISSUE THREAD

**Issue by shiraji** [shiraji/emoji#4]
I felt adding ":" to completion seems less helpful.

For instance, add only emoji name and if developer choose the completion, then add " :$NAME: " text (including spaces)

This can be done by adding `InsertHandler`.

Since it will change behavior, releasing version of this feature will be 1.1.0 or 2.0.0.

**Comment by shiraji** [comment]
After spent one night, I don't think this is good idea. It should show what will be filled in...but adding space may help...let's make another sleep.

**Comment by mallowigi** [comment]
There should be an option whether to use the : completion. Sometimes I just want to write something like "finish feature" and I have the emoji list showing. Then I press tab to press on the commit button and it replaces the last word.

**Comment by shiraji** [comment]
You are right. I had the same problem, too. Let me think about this. 

Providing an option for the behavior is OK to you, @mallowigi ?

**Comment by mallowigi** [comment]
Errm I'm not particularly good with Kotlin, but it can be an interesting task however

**Comment by shiraji** [comment]
OK. I decided to change the behavior of this plugin. It requires to have ':' prefix before showing the list of emoji.
