### ISSUE TITLE
Not working with Markdown

### ISSUE THREAD

**Issue by shiraji** [shiraji/emoji#5]
I'm not sure but it now stop working markdown editor. 

I think I need to remove text "markdown" from README, for now.

**Comment by shiraji** [comment]
OK, it works if I use plain text editor for markdown which is expected...let's consider adding support for "Markdown" type

**Comment by shiraji** [comment]
plugin.xml `<dependancy option="true"` may help this issue.

**Comment by meabed** [comment]
+1 please :)

**Comment by jef** [comment]
+1!

**Comment by shiraji** [comment]
Relate to #18
