### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by mdreizin** [shiraji/emoji#7]
It would be nice to use unscaled images for retina displays.

https://github.com/shiraji/emoji/blob/master/src/main/kotlin/com/github/shiraji/emoji/contributor/EmojiCompletionContributor.kt#L23

**Comment by shiraji** [comment]
I don't have retina display...could you give me screenshot of content assist?

**Comment by mdreizin** [comment]
http://www.webpagefx.com/tools/emoji-cheat-sheet
http://www.jetbrains.org/intellij/sdk/docs/reference_guide/work_with_icons_and_images.html
https://upsource.jetbrains.com/idea-ce/file/idea-ce-1731d054af4ca27aa827c03929e27eeb0e6a8366/platform/util/src/com/intellij/openapi/util/IconLoader.java
https://upsource.jetbrains.com/idea-ce/file/idea-ce-a3e003a945357bcb8d6ff2987bb19b9a70221c8b/platform/util/src/com/intellij/util/ui/IsRetina.java

<img width="344" alt="screen shot 2016-11-10 at 11 06 35 am" src="https://cloud.githubusercontent.com/assets/279122/20168963/e1e90b5a-a735-11e6-96e0-012153e80571.png">

**Comment by shiraji** [comment]
Thanks for info!

**Comment by mdreizin** [comment]
@shiraji Not at all!

**Comment by shiraji** [comment]
@mdreizin Sorry for late. I tried to implement this in https://github.com/shiraji/emoji/tree/support_retina branch.

Uploaded the module in https://plugins.jetbrains.com/plugins/canary/list

Could you try this? 

Documentation of plugin deployment is found http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/deployment.html
